### ISSUE TITLE
No commas in Graph

### ISSUE THREAD

**Issue by deidyomega** [chrisvogt/teacher-salaries#17]
Your graphs dont show commas for the numbers, it took me a few seconds to understand the space meant comma.

Second your website should be hyperlinked.  I understand on the other side of the page you have a button that takes them there, but most people expect urls to be linked to their respective pages.

**Comment by chrisvogt** [comment]
Good catch on the commas. I hadn't even noticed that.

> Since Highcharts 4.1 it defaults to a single space character, which is compatible with ISO and works across Anglo-American and continental European languages. 
> — [lang.thousandsSep documentation](http://api.highcharts.com/highcharts/lang.thousandsSep)

I have updated that configuration option in the above commit and the commas are appearing now.

<img width="569" alt="screen shot 2017-06-27 at 7 10 48 pm" src="https://user-images.githubusercontent.com/1934719/27617778-2f7ae5f0-5b6d-11e7-97ca-406ae895261d.png">

**Comment by chrisvogt** [comment]
As for the hyperlink, I'm going to ignore that one for now because I'm preparing to remove and replace that entire shameless plug. :)

When I merge in and deploy the above fix this comment should automatically close. 🕺🏼

**Comment by chrisvogt** [comment]
Verified fix is live.

![screenshot-teachersalary info-2017-06-27-19-35-33](https://user-images.githubusercontent.com/1934719/27618229-dcc83f62-5b6f-11e7-964a-9140ef9f2c4f.jpeg)
